#include "ShaderStandard.h"

bool ShaderStandard::CreateShader()
{
    std::string vert = std::string(shaderHeader) + skinningDeclarations + skinningFunction +
        "layout(location = 0) in vec3 aPos;\n"
        "layout(location = 1) in vec3 aNormal;\n"
        "layout(location = 2) in vec2 aTexCoord;\n"
        "layout(location = 3) in ivec4 boneIDs;\n"
        "layout(location = 4) in vec4 weights;\n"
        "layout(location = 5) in vec3 aTangent;\n"
        "\n"
        "out VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "} vs_out;\n"
        "\n"
        "void main() {\n"
        "    mat4 skinMat = GetSkinMatrix(boneIDs, weights);\n"
        "    vec4 worldPos = model * skinMat * vec4(aPos, 1.0);\n"
        "    \n"
        "    vs_out.FragPos = worldPos.xyz;\n"
        "    vs_out.TexCoord = aTexCoord;\n"
        "    \n"
        "    mat3 normalMatrix = transpose(inverse(mat3(model * skinMat)));\n"
        "    vec3 N = normalize(normalMatrix * aNormal);\n"
        "    vec3 T = normalize(normalMatrix * aTangent);\n"
        "    T = normalize(T - dot(T, N) * N);\n"
        "    vec3 B = cross(T, N);\n"
        "    \n"
        "    vs_out.Normal = N;\n"
        "    vs_out.TBN = mat3(T, B, N);\n"
        "    \n"
        "    gl_Position = projection * view * worldPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "\n"
        "in VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "} fs_in;\n"
        "\n"
        "uniform sampler2D uAlbedoMap;\n"
        "uniform sampler2D uNormalMap;\n"
        "uniform sampler2D uMetallicMap;\n"
        "uniform sampler2D uOcclusionMap;\n"
        "uniform sampler2D uHeightMap;\n"
        "\n"
        "uniform vec4  uColor;\n"
        "uniform float uHeightScale;\n"
        "uniform float uMetallic;\n"
        "uniform float uRoughness;\n"
        "uniform vec2  uTiling;\n"
        "uniform vec2  uOffset;\n"
        "uniform vec3  viewPos;\n"
        "uniform vec3  lightDir;\n"
        "\n"
        "uniform bool uUseNormalMap;\n"
        "uniform bool uUseMetallicMap;\n"
        "uniform bool uUseOcclusionMap;\n"
        "uniform bool uUseHeightMap;\n"
        "\n"
        "vec2 ParallaxMapping(vec2 texCoords, vec3 viewDir) {\n"
        "    float height = texture(uHeightMap, texCoords).r;\n"
        "    return texCoords - viewDir.xy * (height * uHeightScale);\n"
        "}\n"
        "\n"
        "void main() {\n"
        "    // 0. UVs con Tiling y Offset\n"
        "    vec2 uv = fs_in.TexCoord * uTiling + uOffset;\n"
        "\n"
        "    vec3 viewDir = normalize(viewPos - fs_in.FragPos);\n"
        "\n"
        "    // 1. Parallax Mapping (solo si hay height map activo)\n"
        "    if(uUseHeightMap && uHeightScale > 0.0) {\n"
        "        vec3 viewDirTangent = normalize(transpose(fs_in.TBN) * viewDir);\n"
        "        uv = ParallaxMapping(uv, viewDirTangent);\n"
        "    }\n"
        "\n"
        "    // 2. Normal Mapping (solo si hay normal map activo)\n"
        "    vec3 normal;\n"
        "    if(uUseNormalMap) {\n"
        "        normal = texture(uNormalMap, uv).rgb;\n"
        "        normal = normalize(normal * 2.0 - 1.0);\n"
        "        normal = normalize(fs_in.TBN * normal);\n"
        "    } else {\n"
        "        normal = normalize(fs_in.Normal);\n"
        "    }\n"

        "\n"
        "    // 3. Texturas Base\n"
        "    vec4 texColor = texture(uAlbedoMap, uv);\n"
        "    vec3 albedo = pow(texColor.rgb, vec3(2.2)) * uColor.rgb;\n"
        "\n"
        "    // Metallic: del mapa si existe, sino del slider\n"
        "    float metallic = uUseMetallicMap\n"
        "        ? texture(uMetallicMap, uv).r * uMetallic\n"
        "        : uMetallic;\n"
        "\n"
        "    // Occlusion: del mapa si existe, sino 1.0\n"
        "    float ao = uUseOcclusionMap\n"
        "        ? texture(uOcclusionMap, uv).r\n"
        "        : 1.0;\n"
        "\n"
        "    // 4. LUZ DIRECCIONAL REAL (antes usaba viewDir como luz — bug)\n"
        "    vec3 lightColor = vec3(1.0);\n"
        "    vec3 L = normalize(-lightDir);\n"
        "    float diffFactor = max(dot(normal, L), 0.0);\n"
        "\n"
        "    // 5. ESPECULAR con Blinn-Phong (más correcto que Phong para PBR fake)\n"
        "    float roughness = clamp(uRoughness, 0.05, 1.0);\n"
        "    vec3 H = normalize(L + viewDir);\n"
        "    float specFactor = pow(max(dot(normal, H), 0.0), (1.0 - roughness) * 128.0 + 1.0);\n"
        "\n"
        "    // Color del brillo (metal brilla con su propio albedo, dieléctrico con gris)\n"
        "    vec3 F0 = mix(vec3(0.04), albedo, metallic);\n"
        "    vec3 specular = F0 * specFactor * lightColor;\n"
        "\n"
        "    // Difuso (los metales no tienen difuso)\n"
        "    vec3 diffuse = albedo * diffFactor * (1.0 - metallic) * lightColor;\n"  
        "\n"
        "    // Ambiente\n"
        "    vec3 ambient = albedo * 0.15 * ao;\n"
        "\n"
        "    // 6. RESULTADO\n"
        "    vec3 result = ambient + (diffuse + specular) * ao;\n"
        "\n"
        "    // Gamma Correction\n"
        "    result = pow(max(result, vec3(0.0)), vec3(1.0 / 2.2));\n"
        "\n"
         "    FragColor = vec4(result, texColor.a * uColor.a);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}