#include "ShaderStandard.h"

bool ShaderStandard::CreateShader()
{
    std::string vert = std::string(shaderHeader) + skinningDeclarations + skinningFunction +
        "layout(location = 0) in vec3 aPos;\n"
        "layout(location = 1) in vec3 aNormal;\n"
        "layout(location = 2) in vec2 aTexCoord;\n"
        "layout(location = 3) in ivec4 boneIDs;\n"
        "layout(location = 4) in vec4 weights;\n"
        "layout(location = 5) in vec3 aTangent;\n"
        "\n"
        "out VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "} vs_out;\n"
        "\n"
        "void main() {\n"
        "    mat4 skinMat = GetSkinMatrix(boneIDs, weights);\n"
        "    vec4 worldPos = model * skinMat * vec4(aPos, 1.0);\n"
        "    \n"
        "    vs_out.FragPos = worldPos.xyz;\n"
        "    vs_out.TexCoord = aTexCoord;\n"
        "    \n"
        "    mat3 normalMatrix = transpose(inverse(mat3(model * skinMat)));\n"
        "    vec3 N = normalize(normalMatrix * aNormal);\n"
        "    vec3 T = normalize(normalMatrix * aTangent);\n"
        "    T = normalize(T - dot(T, N) * N); // Gram-Schmidt\n"
        "    vec3 B = cross(N, T);\n"
        "    \n"
        "    vs_out.Normal = N;\n"
        "    vs_out.TBN = mat3(T, B, N);\n" 
        "    \n"
        "    gl_Position = projection * view * worldPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "\n"
        "in VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "} fs_in;\n"
        "\n"
        "uniform sampler2D uAlbedoMap;\n"
        "uniform sampler2D uNormalMap;\n"
        "uniform sampler2D uMetallicMap;\n"
        "uniform sampler2D uOcclusionMap;\n"
        "uniform sampler2D uHeightMap;\n"
        "\n"
        "uniform vec4 uColor;\n"
        "uniform float uHeightScale;\n"
        "uniform vec3 viewPos;\n"
        "\n"
        "void main() {\n"
        "    vec2 uv = fs_in.TexCoord;\n"
        "    \n"
        "    // 1. Normal Mapping\n"
        "    vec3 normal = texture(uNormalMap, uv).rgb;\n"
        "    normal = normalize(normal * 2.0 - 1.0);\n"
        "    normal = normalize(fs_in.TBN * normal); // Convertimos al espacio del mundo\n"
        "\n"
        "    // 2. Albedo + Color\n"
        "    vec4 texColor = texture(uAlbedoMap, uv);\n"
        "    vec3 albedo = texColor.rgb * uColor.rgb;\n"
        "\n"
        "    // 3. Occlusión Ambiental (AO)\n"
        "    float ao = texture(uOcclusionMap, uv).r;\n"
        "\n"
        "    // 4. Iluminación (Direccional + Ambiente)\n"
        "    vec3 lightDir = normalize(vec3(0.5, 1.0, 0.3));\n"
        "    float diff = max(dot(normal, lightDir), 0.0);\n"
        "    \n"
        "    // Ambiente reforzado para evitar oscuridad (mezclado con AO)\n"
        "    vec3 ambient = vec3(0.4) * albedo * ao;\n"
        "    vec3 diffuse = diff * albedo;\n"
        "\n"
        "    vec3 result = diffuse + ambient;\n"
        "\n"
        "    // 5. Corrección Gamma (Para brillo natural)\n"
        "    result = pow(result, vec3(1.0 / 2.2));\n"
        "\n"
        "    FragColor = vec4(result, texColor.a * uColor.a);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}